### ISSUE TITLE
MinDate, MaxDate bug

### ISSUE THREAD

**Issue by Kml55** [jjobes/SlideDateTimePicker#10]
Hi,

I am using minDate and maxDate functions, it works in day level but not working in hour, minutes level. For example, If I set minDate; now as 30.07.2015 13:28, I can choose 30.07.2015 12:28.. minDate and maxDate functions must also work for hour and minutes thresholds..

Thx.

**Comment by jjobes** [comment]
Hi Kml55,

Thanks for your message.

That's actually the intended functionality for `setMinDate()` and `setMaxDate()`. They only affect the DatePicker and so just have day granularity.

The extra functionality you're looking for could be easily added to the library. Please take a look at the source.  Feel free to fork the library and submit a PR.

Take care,

Jason
