### ISSUE TITLE
Wrong way of setting ViewPager height

### ISSUE THREAD

**Issue by alexrainman** [jjobes/SlideDateTimePicker#16]
The way you set the ViewPager height OnMeasure makes the DatePicker move to the left when you touch it.

Replace it with this code:

```
int height = 0;
for(int i = 0; i < getChildCount(); i++) {
    View child = getChildAt(i);
    child.measure(widthMeasureSpec, MeasureSpec.makeMeasureSpec(0, MeasureSpec.UNSPECIFIED));
    int h = child.getMeasuredHeight();
    if(h > height) height = h;
}

heightMeasureSpec = MeasureSpec.makeMeasureSpec(height, MeasureSpec.EXACTLY);

super.onMeasure(widthMeasureSpec, heightMeasureSpec);
```

And problem fixed!

**Comment by jjobes** [comment]
Hey Alex,

Could you please give me some more details about what exactly the error is and how to reproduce it?

I'm not sure what you mean by "makes the DatePicker move to the left when you touch it".

Thanks!

Jason

**Comment by alexrainman** [comment]
I updated the library to the latest SDK version. When you touch the DatePicker and change the date, somehow it's height change and, instead of being centered it gets moved to the left (aligned to the left).
I changed the code with the one i provided and the issue is gone :)

**Comment by jjobes** [comment]
Can you give me the details of the device you saw the error on?

**Comment by alexrainman** [comment]
Google Nexus 5 Android 5.1

**Comment by jjobes** [comment]
I just reproduced it on an emulator and I see what you mean. Let me take a closer look at this and I'll report back later.

**Comment by jjobes** [comment]
Okay, looks good to me!  Did you want to submit a PR or do you just want me to push the changes and give you credit for it in the Changelog?

**Comment by alexrainman** [comment]
Just include the fix my friend. The credit is all yours for this amazing library. I migrated it to C# and im using it in Xamarin :)

**Comment by jjobes** [comment]
Okay, will do!  I'm glad you find it useful :)

**Comment by alexrainman** [comment]
More than useful. I will include it in a free cross platform component for Xamarin.Forms and of course, give u the credit ;)

**Comment by jjobes** [comment]
Wow, that sounds great!  Best of luck on your project!

**Comment by alexrainman** [comment]
Cheers for u 2!
