### ISSUE TITLE
Maintain consistent version information

### ISSUE THREAD

**Issue by johnjohndoe** [jjobes/SlideDateTimePicker#4]
I noticed that you **updated the version number** in the [CHANGELOG section](https://github.com/jjobes/SlideDateTimePicker/commit/294a3ab99a36055baef4525c2aad2025328ff4d9#diff-04c6e90faac2675aa89e2176d2eec7d8R112) a while ago. I could however **not** find the same version being set for the library such as in _AndroidManifest.xml_. Please make sure these are in sync.

Further, it would be very helpful if you could at the same time add a **version tag** to the repository.

``` bash
$ git checkout 7ad978903e3bc5f2425ddb0b7625579413f2a35e
$ git tag -a "v.1.0.0" -m "Initial release."
$ git checkout 294a3ab99a36055baef4525c2aad2025328ff4d9
$ git tag -a "v.1.0.1" -m "Builder methods rewrite."
$ git checkout master
$ git push origin master --tags
```

This will allow to see fast and convenient what is going on. The tag should contain a **short summary** of what has been happening since the last version number. The long description can be found in the CHANGELOG section (which should be a separate file in the future when it becomes too long).

**Comment by jjobes** [comment]
Thanks, johnjohndoe. I updated the manifest version info and added version tags.
