### ISSUE TITLE
Android O issue

### ISSUE THREAD

**Issue by ashwingkrish** [jjobes/SlideDateTimePicker#43]
The dialog is getting displayed, but the actual selector for the date and time is not visible so it cannot be displayed on Android O only.

**Comment by Gaetano-Dati** [comment]
Has It been fixed?

**Comment by pizza** [comment]
I have the same issue.

**Comment by pwiniars** [comment]
I've managed to fix this, along with #45. You can get it from my forked repo by adding this to gradle: compile("com.github.pwiniars:SlideDateTimePicker:v1.0.7")

**Comment by pwiniars** [comment]
I've managed to fix this issue, you can get it from my fork: compile("com.github.pwiniars:SlideDateTimePicker:v1.0.8")
