### ISSUE TITLE
Warn about use of reflection

### ISSUE THREAD

**Issue by iPaulPro** [jjobes/SlideDateTimePicker#6]
You should add a warning to the readme that clearly states that this library is using a bunch of reflection in the Picker classes.

**Comment by jjobes** [comment]
Thank you, iPaulPro.The readme has been updated.

**Comment by m00shm00sh** [comment]
This could somewhat be done without reflection. See `Resources.getSystem().getIdentifier(name, "id", "android")` to get the `id`. Works for all of `numberpicker_input`, `hour`, `minute`, and `divider`. This is the approach I used in the first iteration of my picker.

Reflection for the selection divider seems inevitable, though, as it's a private field and annotated with `@UnsupportedAppUsage`
