### ISSUE TITLE
build.gradle -> dependencies: Can't put direct  compile ' github  '

### ISSUE THREAD

**Issue by ajaykeshri** [jjobes/SlideDateTimePicker#7]
dependencies {
    compile 'com.github.jjobes.slidedatetimepicker'
}
I am getting   below error :
Error:(26, 0) Supplied String module notation 'com.github.jjobes.slidedatetimepicker' is invalid. Example notations: 'org.gradle:gradle-core:2.2', 'org.mockito:mockito-core:1.9.5:javadoc'.

So please tell me what is addition dependencies we have to add.This is also not in Maven.

**Comment by jjobes** [comment]
See if this works:

`compile project(':slideDateTimePicker')`

**Comment by ajaykeshri** [comment]
Thanks for fast response,
I did same , its working
Please update same is description Setup .

On Tue, Feb 17, 2015 at 11:49 AM, jjobes notifications@github.com wrote:

> See if this works:
> 
> compile project(':slideDateTimePicker')
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jjobes/SlideDateTimePicker/issues/7#issuecomment-74622263
> .

## 

*Thanks and Best Regards, *

_AJAY KUMAR9740017333_

**Comment by jjobes** [comment]
Sure, no problem!
