### ISSUE TITLE
Limit to show only the datepicker

### ISSUE THREAD

**Issue by tusharaga** [jjobes/SlideDateTimePicker#9]
Hi jjobes, Thanks for creating this awesome library , need to know how can I limit this picker so that it just shows the date picker instead of datetime picker.

**Comment by jjobes** [comment]
Hi tusharaga,

There is no built-in functionality to only show the date picker.  You would just have to use a normal date picker for that.

**Comment by tusharaga** [comment]
Okay , Thanks

**Comment by fparkar** [comment]
Below is how I made

In **_private void setupViews(View v)_**, I added a line as below.

***mSlidingTabLayout.setVisibility(View.INVISIBLE);***

This way I just see date picker and time picker get hided...
